name: re_state_action_test
description: A testing library to make testing re_state_action easier. Built to be used with the re_state_action package.
repository:  https://github.com/alvarobcprado/re_state_action_test
issue_tracker: https://github.com/alvarobcprado/re_state_action_test/issues
version: 0.0.1

environment:
  sdk: '>=2.12.0 <4.0.0'

dependencies:
  meta: ^1.8.0
  mocktail: ^0.3.0
  re_state_action: ^0.0.12
  test: ^1.24.2

dev_dependencies:
  very_good_analysis: ^4.0.0+1